service: digitar-backend

provider:
  name: aws
  runtime: python3.6
  stage: prod
  region: eu-west-1
  apiKeys:
      - iotkey

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: digitar/hello
          method: get
          cors: true
          private: true
  hello-pub:
    handler: handler.hello
    events:
      - http:
          path: digitar/hellopub
          method: get
          cors: true
          private: false
  put:
    handler: handler.put
    events:
      - http:
          path: digitar/put
          method: post
          cors: true
          private: false
